[tool.black]
  skip-string-normalization = true
  include = '''
  (
       \.pyi?$
     | \.py\.in$
  )
  '''
  exclude = '''
  (
       src/bindings/python/bt2/build/
     | src/bindings/python/bt2/setup\.py$
     | src/bindings/python/bt2/bt2/native_bt\.py$
     | src/bindings/python/bt2/bt2/version\.py$
     | tests/utils/python/tap

  )
  '''
