#!/bin/bash
#
# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright (C) 2020 Philippe Proulx <pproulx@efficios.com>

if [ "x${BT_TESTS_SRCDIR:-}" != "x" ]; then
	UTILSSH="$BT_TESTS_SRCDIR/utils/utils.sh"
else
	UTILSSH="$(dirname "$0")/../../utils/utils.sh"
fi

# shellcheck source=../../utils/utils.sh
source "$UTILSSH"

reldir=lib/prepostconds
export BT_TESTS_LIB_PREPOSTCONDS_BUILDDIR="$BT_TESTS_BUILDDIR/$reldir"
run_python_bt2_test "$BT_TESTS_SRCDIR/$reldir" test.py
